// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	model "github.com/delyke/urlShortener/internal/model"
)

// MockURLRepository is a mock of URLRepository interface.
type MockURLRepository struct {
	ctrl     *gomock.Controller
	recorder *MockURLRepositoryMockRecorder
}

// MockURLRepositoryMockRecorder is the mock recorder for MockURLRepository.
type MockURLRepositoryMockRecorder struct {
	mock *MockURLRepository
}

// NewMockURLRepository creates a new mock instance.
func NewMockURLRepository(ctrl *gomock.Controller) *MockURLRepository {
	mock := &MockURLRepository{ctrl: ctrl}
	mock.recorder = &MockURLRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLRepository) EXPECT() *MockURLRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockURLRepository) CreateUser() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockURLRepositoryMockRecorder) CreateUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockURLRepository)(nil).CreateUser))
}

// DeleteURLsByUser mocks base method.
func (m *MockURLRepository) DeleteURLsByUser(userID int64, URLs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteURLsByUser", userID, URLs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteURLsByUser indicates an expected call of DeleteURLsByUser.
func (mr *MockURLRepositoryMockRecorder) DeleteURLsByUser(userID, URLs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteURLsByUser", reflect.TypeOf((*MockURLRepository)(nil).DeleteURLsByUser), userID, URLs)
}

// GetOriginalLink mocks base method.
func (m *MockURLRepository) GetOriginalLink(shortedURL string) (string, *bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalLink", shortedURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOriginalLink indicates an expected call of GetOriginalLink.
func (mr *MockURLRepositoryMockRecorder) GetOriginalLink(shortedURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalLink", reflect.TypeOf((*MockURLRepository)(nil).GetOriginalLink), shortedURL)
}

// GetShortURLByOriginal mocks base method.
func (m *MockURLRepository) GetShortURLByOriginal(originalURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortURLByOriginal", originalURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortURLByOriginal indicates an expected call of GetShortURLByOriginal.
func (mr *MockURLRepositoryMockRecorder) GetShortURLByOriginal(originalURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortURLByOriginal", reflect.TypeOf((*MockURLRepository)(nil).GetShortURLByOriginal), originalURL)
}

// GetURLsByUserID mocks base method.
func (m *MockURLRepository) GetURLsByUserID(userID int64) (*[]model.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLsByUserID", userID)
	ret0, _ := ret[0].(*[]model.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLsByUserID indicates an expected call of GetURLsByUserID.
func (mr *MockURLRepositoryMockRecorder) GetURLsByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLsByUserID", reflect.TypeOf((*MockURLRepository)(nil).GetURLsByUserID), userID)
}

// Ping mocks base method.
func (m *MockURLRepository) Ping() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockURLRepositoryMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockURLRepository)(nil).Ping))
}

// Save mocks base method.
func (m *MockURLRepository) Save(originalURL, shortedURL string, userID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", originalURL, shortedURL, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockURLRepositoryMockRecorder) Save(originalURL, shortedURL, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockURLRepository)(nil).Save), originalURL, shortedURL, userID)
}

// SaveBatch mocks base method.
func (m *MockURLRepository) SaveBatch(records []model.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatch", records)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBatch indicates an expected call of SaveBatch.
func (mr *MockURLRepositoryMockRecorder) SaveBatch(records interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatch", reflect.TypeOf((*MockURLRepository)(nil).SaveBatch), records)
}
