version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: shortener-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shortener
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data:
